Feature/request methods
starkbank/sdk-node pull request #124
Opened 2024-06-10 21:14 UTC by leoKagohara-Stark

2024-06-25 01:21 UTC, luistarkbank commented on README.md
> +# request
Resquest

2024-06-25 01:21 UTC, luistarkbank commented on README.md
> +## patch
PATCH

2024-06-25 01:21 UTC, luistarkbank commented on README.md
> +# request
ue, dnv ??

2024-06-25 01:21 UTC, luistarkbank commented on README.md
> +## POST
se pá vc duplicou

2024-06-25 01:21 UTC, luistarkbank commented on sdk/event/event.js
> +    if (user == null){
acho que não precisa disso

2024-06-25 01:21 UTC, luistarkbank commented on sdk/request/request.js
> +     * @param query [object, default None]: Query parameters. ex: {"limit": 1, "status": paid}
"paid"

2024-06-25 01:21 UTC, luistarkbank commented on sdk/request/request.js
> +    return rest.getRaw(path, query, prefix, user);
adicionar raiseException

2024-06-25 01:21 UTC, luistarkbank commented on sdk/request/request.js
> +    return rest.postRaw(path, body, prefix, user);
same

2024-06-25 01:21 UTC, luistarkbank commented on sdk/request/request.js
> +    return rest.patchRaw(path, body, prefix, user);
same

2024-06-25 01:21 UTC, luistarkbank commented on sdk/request/request.js
> +    return rest.putRaw(path, body, prefix, user);
same

2024-06-25 01:21 UTC, luistarkbank commented on sdk/request/request.js
> +    return rest.deleteRaw(path, body, prefix, user);
same

2024-06-25 01:21 UTC, luistarkbank commented on sdk/utils/rest.js
> +        prefix
adicionar raiseException

2024-06-25 01:21 UTC, luistarkbank commented on sdk/utils/rest.js
> +        prefix
same

2024-06-25 01:21 UTC, luistarkbank commented on sdk/utils/rest.js
> +        prefix
same

2024-06-25 01:21 UTC, luistarkbank commented on sdk/utils/rest.js
> +        prefix
same

2024-06-25 01:21 UTC, luistarkbank commented on sdk/utils/rest.js
> +        prefix
same

2024-06-25 01:21 UTC, luistarkbank commented on tests/testCorporateCard.js
> +// describe('TestCorporateCardPage', function () {
?? kjk

2024-06-25 01:21 UTC, luistarkbank commented on tests/testCorporateHolder.js
> +        assert(ids.length == 2);
esse teste ta passando ??

2024-06-25 01:21 UTC, luistarkbank commented on tests/testCorporatePurchase.js
> +        content = '{"event": {"created": "2024-06-07T23:19:39.606017+00:00", "id": "6447612198649856", "log": {"corporateTransactionId": "", "created": "2024-06-07T23:19:38.893018+00:00", "descriptio
melhor fazer raplace nesses dados jkj

2024-06-25 01:21 UTC, luistarkbank commented on tests/testPaymentRequest.js
> +        const requests = await starkbank.paymentRequest.query({ centerId: "6474628142727168", limit: 5 });
não sei se era o objetivo, mas esse teste não é dinamico

2024-06-25 01:21 UTC, luistarkbank commented on tests/testPaymentRequest.js
> +            [page, cursor] = await starkbank.paymentRequest.page({ limit: 5, cursor: cursor, centerId: "6474628142727168"});
same

2024-06-25 01:21 UTC, luistarkbank commented on tests/testRequest.js
> +        let query={"limit": 10, "status": "paid"};
espaço no "="

2024-06-25 01:21 UTC, luistarkbank commented on tests/testRequest.js
> +        assert(final_status["content"]["transfer"]["status"] == 'canceled')
camelCase

2024-06-25 01:21 UTC, luistarkbank commented on tests/utils/paymentRequest.js
> +            centerId: "6474628142727168",
same

2024-06-25 19:15 UTC, leoKagohara-Stark commented on tests/testCorporateHolder.js
> +        assert(ids.length == 2);
Tá sim

2024-06-25 19:21 UTC, leoKagohara-Stark commented on tests/testCorporatePurchase.js
> +        content = '{"event": {"created": "2024-06-07T23:19:39.606017+00:00", "id": "6447612198649856", "log": {"corporateTransactionId": "", "created": "2024-06-07T23:19:38.893018+00:00", "descriptio
Conversamos e chegamos na conclusão que não temos ganhos em gerar um evento com os dados no padrão da documentação.

2024-06-25 22:37 UTC, luistarkbank commented on tests/testCorporateHolder.js
> +        assert(ids.length == 2);
se eu entendi o codigo vc ta fazendo o request passando o limit 1 porem fazendo um assert de dois ids ?? jkj

2024-06-28 01:46 UTC, luistarkbank commented on README.md
> +    let example_id = "5699165527090460"
camelCase

2024-06-28 01:46 UTC, luistarkbank commented on README.md
> +    let invoice = await starkbank.request.get(`/invoice/${example_id}`);
same

2024-06-28 01:46 UTC, luistarkbank commented on README.md
> +    let invoice = await starkbank.request.get(`/invoice/log/${example_id}`);
same

2024-06-28 01:46 UTC, luistarkbank commented on README.md
> +example_id = "5155165527080960"
same

2024-06-28 01:46 UTC, luistarkbank commented on README.md
> +    path=f"/transfer/{example_id}",
da um check geral

2024-06-28 01:46 UTC, luistarkbank commented on sdk/request/request.js
> +     * @param body [dict]: request parameters. ex: {"invoices": [{"amount": 100, "name": "Iron Bank S.A.", "taxId": "20.018.183/0001-80"}]}
eu acho que nao passa body em delete

2024-06-28 01:46 UTC, luistarkbank commented on tests/testCorporateHolder.js
> +        assert(ids.length == 2);
só deixei esse comentario aberto pra dps se voce tiver tempo me explicar como isso funciona

2024-07-01 14:01 UTC, leoKagohara-Stark commented on sdk/request/request.js
> +     * @param body [dict]: request parameters. ex: {"invoices": [{"amount": 100, "name": "Iron Bank S.A.", "taxId": "20.018.183/0001-80"}]}
Eu deixei por ser um parametro que está mapeado no deleteId que já estava implementado, apesar de não passarmos o body, deixei apenas para manter o padrão

2024-07-01 14:45 UTC, luistarkbank requested changes

2024-07-01 14:45 UTC, luistarkbank commented on sdk/request/request.js
> +     * @param query [object, default None]: Query parameters. ex: {"limit": 1, "status": "paid"}
query não é required

2024-07-01 14:45 UTC, luistarkbank commented on sdk/request/request.js
> +     * @param body [dict]: request parameters. ex: {"invoices": [{"amount": 100, "name": "Iron Bank S.A.", "taxId": "20.018.183/0001-80"}]}
dict

2024-07-02 21:06 UTC, danielterra-stark approved these changes

2024-07-03 12:08 UTC, merged