Add merchantSession and merchantSessionPurchase resources
starkbank/sdk-node pull request #127
Opened 2024-07-12 23:51 UTC by luistarkbank

2024-07-13 00:51 UTC, cdottori-stark requested changes

2024-07-13 00:51 UTC, cdottori-stark commented on sdk/merchantSessionPurchase/index.js
> +const merchantSessionPurchase = require('./merchantPurchase.js');
Não faltou o session no nome do arquivo?

2024-07-14 18:01 UTC, leoKagohara-Stark approved these changes

2024-07-15 22:21 UTC, cdottori-stark approved these changes

2024-07-15 22:21 UTC, merged