Feature/hidden fields our number boleto pdf
starkbank/sdk-node pull request #20
Opened 2020-09-18 00:01 UTC by vidalstark

2020-09-21 18:37 UTC, cdottori-stark requested changes

2020-09-21 18:37 UTC, cdottori-stark commented on CHANGELOG.md
> +- hiddenFields parameter to Boleto.pdf
acho que o módulo no js ta com letra minúscula -> boleto.pdf

2020-09-21 18:37 UTC, cdottori-stark commented on CHANGELOG.md
> +- ourNumber attribute to Boleto
esse aqui ok pq é a instancia mesmo

2020-09-21 18:37 UTC, cdottori-stark commented on sdk/boleto/boleto.js
> +     * @param ourNumber [string, default null]: Boleto our-number. ex:"10131474"
acho que vale a pena explicar melhor isso aqui

2020-09-21 21:59 UTC, vidalstark commented on CHANGELOG.md
> +- hiddenFields parameter to Boleto.pdf
Verdade

2020-09-21 22:02 UTC, vidalstark commented on CHANGELOG.md
> +- ourNumber attribute to Boleto
Ok

2020-09-21 22:02 UTC, vidalstark commented on sdk/boleto/boleto.js
> +     * @param ourNumber [string, default null]: Boleto our-number. ex:"10131474"
Done

2020-09-27 17:22 UTC, cdottori-stark approved these changes

2020-09-27 17:22 UTC, merged