Feature/tax payment
starkbank/sdk-node pull request #22
Opened 2020-10-05 22:29 UTC by vidalstark

2020-10-09 14:42 UTC, LucasStarkBank requested changes

2020-10-09 14:42 UTC, LucasStarkBank commented on tests/utils/businesses/businessesInfo.js
> +const taxes = [
Será que não é legal por isso num json e pedir para o Javascript carregar o JSON? Deixa o código mais enxuto.

2020-10-09 14:42 UTC, LucasStarkBank commented on tests/utils/businesses/businessesInfo.js
> +const utilities = [
Isso também pode ficar em outro json.

2021-07-14 14:57 UTC, cdottori-stark requested changes

2021-07-14 14:57 UTC, cdottori-stark commented on README.md
> +### Create tax payment
### Create tax payments

2021-07-14 14:57 UTC, cdottori-stark commented on README.md
> +### Get tax payment
### Get a tax payment

2021-07-14 14:57 UTC, cdottori-stark commented on README.md
> +### Get tax payment PDF
### Get a tax payment PDF

2021-07-14 14:57 UTC, cdottori-stark commented on README.md
> +### Delete tax payment
### Delete a tax payment

2021-07-14 14:57 UTC, cdottori-stark commented on README.md
> +### Get tax payment log
### Get a tax payment log

2021-07-14 14:57 UTC, cdottori-stark commented on README.md
> +```
Acho que essas entradas todas de Transaction foram a mais, devem estar repetidas

2021-07-14 14:57 UTC, cdottori-stark commented on sdk/taxPayment/log/index.js
> +exports.query = log.query;
newline

2021-07-14 14:57 UTC, cdottori-stark commented on sdk/taxPayment/taxPayment.js
> +     * @param line [string, default null]: Number sequence that describes the payment. Either 'line' or 'bar_code' parameters are required. If both are sent, they must match. ex: '34191.09008 63571.2
bar_code -> barCode

2021-07-14 14:57 UTC, cdottori-stark commented on sdk/taxPayment/taxPayment.js
> +     * @returns user [Project object]: Project object. Not necessary if starkbank.user was set before function call
Acho que precisa complementar todas essas docstrings de usar com o Organization (copiar e colar o padrão novo)

2021-07-14 14:57 UTC, cdottori-stark commented on sdk/taxPayment/taxPayment.js
> +};
newline

2021-07-14 14:57 UTC, cdottori-stark commented on tests/utils/businesses/businessesInfo.js
> +exports.randomBusiness = randomBusiness;
newline

2021-07-14 14:57 UTC, cdottori-stark commented on tests/utils/businesses/index.js
> +exports.randomBusiness = businessInfo.randomBusiness;
newline

2021-07-14 14:57 UTC, cdottori-stark commented on tests/utils/businesses/taxes.json
> +]
newline

2021-07-14 14:57 UTC, cdottori-stark commented on tests/utils/businesses/utilities.json
> +]
newline

2021-07-14 14:57 UTC, cdottori-stark commented on tests/utils/nonBoletoPayment.js
> +exports.generateExampleNonBoletoPaymentsJson = generateExampleNonBoletoPaymentsJson;
newline

2021-07-14 14:57 UTC, cdottori-stark commented on tests/utils/taxPayment.js
> +exports.generateExampleTaxPaymentsJson = generateExampleTaxPaymentsJson;
newline

2021-07-14 17:14 UTC, cdottori-stark approved these changes

2021-07-14 17:15 UTC, merged