Add Types for Typescript
starkbank/sdk-node pull request #72
Opened 2022-06-21 19:30 UTC by xavier-stark

2022-06-23 17:30 UTC, adryanalencar requested changes

2022-06-23 17:30 UTC, adryanalencar commented on types/boletoPayment/boletoPayment.d.ts
> +        tags? : string | null[]
Meio estranho `null[]`

2022-06-23 17:30 UTC, adryanalencar commented on types/darfPayment/darfPayment.d.ts
> +            tags?: string | null[], status?: string | null, amount?: number | null, fee?: number | null, transactionIds?: string | null[], updated?: string | null,
`null[]` ?

2022-06-23 17:30 UTC, adryanalencar commented on types/brcodePayment/brcodePayment.d.ts
> +        function pdf(id: string, params?:{ user?: Project | Organization | null}): any;
qual o retorno dessa função?

2022-06-23 17:30 UTC, adryanalencar commented on types/darfPayment/darfPayment.d.ts
> +        export function create(payments: any, params?:{ user?: Project | Organization | null}): Promise<DarfPayment[]>;
não seria `payments: DarfPayment[]`?

2022-06-23 17:30 UTC, adryanalencar commented on types/darfPayment/darfPayment.d.ts
> +        export function pdf(id: string, params?:{ user?: Project | Organization | null}): any;
Qual o retorno dessa função?

2022-06-23 17:30 UTC, adryanalencar commented on types/darfPayment/darfPayment.d.ts
> +        export function pdf(id: string, params?:{ user?: Project | Organization | null}): any;
`Buffer`

2022-06-23 17:30 UTC, adryanalencar commented on types/event/event.d.ts
> +        log: any
Não seria
`log: boleto.Log | taxPayment.Log ...` ?

2022-06-23 17:30 UTC, adryanalencar commented on types/event/event.d.ts
> +        constructor(created: string, isDelivered: string, subscription: string, log: any, id: string, workspaceId: string)
Aqui também `log: boleto.Log | taxPayment.Log ...`

2022-06-23 17:30 UTC, adryanalencar commented on types/boletoPayment/boletoPayment.d.ts
> +        export function pdf(id: string, params?:{ user?: Project | Organization | null}): any;
return type `Buffer`

2022-06-23 17:30 UTC, adryanalencar commented on types/event/event.d.ts
> +        export function parse(params?: {content: string, signature: string, user?: Project | Organization}): any;
Aqui o return não seria Event?

2022-06-23 17:30 UTC, adryanalencar commented on types/index.d.ts
> +            function captureStackTrace(p0: any, p1: any): any;
Tipo?

2022-06-23 17:30 UTC, adryanalencar commented on types/index.d.ts
> +            function captureStackTrace(p0: any, p1: any): any;
Tipo?

2022-06-23 17:30 UTC, adryanalencar commented on types/index.d.ts
> +            function captureStackTrace(p0: any, p1: any): any;
Tipo?

2022-06-23 17:30 UTC, adryanalencar commented on types/taxPayment/taxPayment.d.ts
> +        export function pdf(id: string, params?:{ user?: Project | Organization | null}): any;
return type `Buffer`

2022-06-23 17:30 UTC, adryanalencar commented on types/test/testBoleto.ts
> +    let page: any = null;
`page : string`?

2022-06-23 17:30 UTC, adryanalencar commented on types/test/testBoletoHolmes.ts
> +    let holmes: any = [];
`let holmes : starkbank.BoletoHolmes[] = []`?

2022-06-23 17:30 UTC, adryanalencar commented on types/test/testBoletoHolmes.ts
> +    let page: any = null;
`page: string`

2022-06-23 17:30 UTC, adryanalencar commented on types/test/testBoletoHolmesLog.ts
> +    let page: any = null;
Corrige aqui e nos demais lugares

2022-06-23 18:20 UTC, xavier-stark commented on types/boleto/boleto.d.ts
> +        readonly id? : string | null
Discutido internamente, resolvido retirar ? e deixar | null

2022-06-30 17:12 UTC, cdottori-stark commented on sdk/utils/request.js
> +        'sandbox': 'https://development.api.starkbank.com/' + version
wut

2022-06-30 17:15 UTC, cdottori-stark commented on types/darfPayment/darfPayment.d.ts
> +         * TaxPayment object
wut

2022-06-30 17:17 UTC, cdottori-stark commented on types/institution/institution.d.ts
> +    export class Institution{
arrumar espaços

2022-06-30 17:18 UTC, cdottori-stark commented on types/invoice/invoice.d.ts
> +         * @param limit     [integer, default null]: maximum number of objects to be retrieved. Unlimited if null. ex: 35
formatação diferente

2022-06-30 20:44 UTC, cdottori-stark approved these changes

2022-06-30 21:18 UTC, adryanalencar approved these changes

2022-06-30 21:26 UTC, merged